### ISSUE TITLE
Support secured connection to Elasticsearch

### ISSUE THREAD

**Issue by lukas-vlcek** [ViaQ/watches-cli#1]
When communicating with Elasticsearch in secured environment we need to support security appropriately. For example it is possible to create an [external Elasticsearch route with OpenShift Logging](http://richmegginson.livejournal.com/28981.html) and the communication then requires proper handling of security certificates.

- [x] Add security related options
- [x] Install and configure [SearchGuard plugin](https://github.com/floragunncom/search-guard) to Elasticsearch instance in CI tests
- [x] Use [secured `elasticsearch-py` client](https://github.com/elastic/elasticsearch-py/issues/344) connection
- [x] Document how to install and configure SG plugin for local tests

**Comment by lukas-vlcek** [comment]
@richm I think I ran out of ideas why security is not working 😢 Even on Linux this is not working (both my local _Fedora 23_ or _Ubuntu 12.04.5 LTS_ on Travis ). [cURL with certificates is working in testing scripts](https://travis-ci.org/ViaQ/watches-cli/builds/181631869#L743) but no luck with elasticsearch-py client [tests using the same certificates](https://github.com/ViaQ/watches-cli/blob/1/tests/commands/secure_support.py#L12-L15). The [error message](https://travis-ci.org/ViaQ/watches-cli/builds/181631869#L1830) does not help me much.

Do you think you could run your eyes over this? All the code is in [branch 1](https://github.com/ViaQ/watches-cli/tree/1). All the ES client config happens in [base.py](https://github.com/ViaQ/watches-cli/blob/1/watches/commands/base.py#L34-L39).

I documented how to test it locally with all the security install and setup, see <https://github.com/ViaQ/watches-cli/blob/1/tests/Testing.md#testing-manually>.

If you just want to run python tests against **local non-secured ES node**, then skip SG stuff and just change this [`True`](https://github.com/ViaQ/watches-cli/blob/1/tests/commands/secure_support.py#L24) to `False`.

**Comment by richm** [comment]
The problem is that searchguard generates its certificates with the X509v3 Subject Alternative Name extension with the value Registered ID:1.2.3.4.5.5. python ssl doesn't like this. origin-aggregated-logging had to disable this extension in externally facing certs: https://github.com/openshift/origin-aggregated-logging/blob/master/deployer/scripts/util.sh#L17
I think we have to do the same.

openssl bug: https://bugzilla.redhat.com/show_bug.cgi?id=1402153

python bug: https://bugzilla.redhat.com/show_bug.cgi?id=1402154
